// <auto-generated />
using System;
using Group4Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group4Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20260406052429_InMemoryDB")]
    partial class InMemoryDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Group4Flight.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            ImageName = "delta.png",
                            Name = "Delta Air Lines"
                        },
                        new
                        {
                            AirlineId = 2,
                            ImageName = "united.png",
                            Name = "United Airlines"
                        },
                        new
                        {
                            AirlineId = 3,
                            ImageName = "american.png",
                            Name = "American Airlines"
                        },
                        new
                        {
                            AirlineId = 4,
                            ImageName = "southwest.png",
                            Name = "Southwest Airlines"
                        });
                });

            modelBuilder.Entity("Group4Flight.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Emission")
                        .HasColumnType("REAL");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Airbus A321",
                            AirlineId = 1,
                            ArrivalTime = new TimeSpan(0, 13, 15, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 10, 0, 0, 0),
                            Emission = 190.0,
                            FlightCode = "DL201",
                            From = "Chicago",
                            Price = 245m,
                            To = "Boston"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Boeing 787-9",
                            AirlineId = 2,
                            ArrivalTime = new TimeSpan(0, 15, 20, 0, 0),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 11, 45, 0, 0),
                            Emission = 280.0,
                            FlightCode = "UA310",
                            From = "Houston",
                            Price = 355m,
                            To = "San Francisco"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Airbus A330",
                            AirlineId = 3,
                            ArrivalTime = new TimeSpan(0, 10, 40, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 7, 20, 0, 0),
                            Emission = 175.0,
                            FlightCode = "AA478",
                            From = "New York",
                            Price = 610m,
                            To = "Orlando"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Boeing 737-900",
                            AirlineId = 4,
                            ArrivalTime = new TimeSpan(0, 15, 25, 0, 0),
                            CabinType = "Basic Economy",
                            Date = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 13, 5, 0, 0),
                            Emission = 205.0,
                            FlightCode = "WN508",
                            From = "Los Angeles",
                            Price = 175m,
                            To = "Seattle"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Airbus A220",
                            AirlineId = 1,
                            ArrivalTime = new TimeSpan(0, 10, 10, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 8, 15, 0, 0),
                            Emission = 160.0,
                            FlightCode = "DL630",
                            From = "Miami",
                            Price = 215m,
                            To = "Atlanta"
                        });
                });

            modelBuilder.Entity("Group4Flight.Models.Flight", b =>
                {
                    b.HasOne("Group4Flight.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Group4Flight.Models.Airline", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
